# Generated by Django 5.1.15 on 2026-09-14 16:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQueueSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.localdate, unique=True, verbose_name='Tanggal Antrian')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='Nomor Urut Terakhir')),
            ],
            options={
                'verbose_name': 'Urutan Antrian Harian',
                'verbose_name_plural': 'Urutan Antrian Harian',
                'db_table': 'queue_gate_daily_sequence',
            },
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Tanggal Operasional')),
                ('no_antrian', models.CharField(db_index=True, max_length=20, verbose_name='Nomor Antrian (Format Q-0001)')),
                ('status', models.CharField(choices=[('MENUNGGU', 'Menunggu Buffer Gate'), ('PROSES', 'Sedang Proses di Booth / Yard'), ('TERTAHAN', 'Tertahan / Hold'), ('SELESAI', 'Selesai di Yard'), ('KELUAR', 'Keluar Terminal (Gate Out)')], db_index=True, default='MENUNGGU', max_length=25, verbose_name='Status Antrian')),
                ('alasan_tertahan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alasan Tertahan (Hold)')),
                ('gerbang_lane', models.CharField(choices=[('Lane 01 - Dry In', 'Lane 01 — Dry In'), ('Lane 02 - Reefer', 'Lane 02 — Reefer'), ('Lane 03 - Auto OCR', 'Lane 03 — Auto OCR'), ('Lane 04 - Trouble', 'Lane 04 — Trouble / Hold'), ('Lane 05 - Empty', 'Lane 05 — Empty Return'), ('Lane 06 - Dedicated', 'Lane 06 — Dedicated'), ('Out 01 - Dispatch', 'Out 01 — Dispatch'), ('Out 02 - Bypass', 'Out 02 — Bypass')], default='Lane 01 - Dry In', max_length=50, verbose_name='Lane / Jalur Gerbang')),
                ('booth', models.CharField(default='Gate Inbound 01', max_length=50, verbose_name='Booth Pendaftaran')),
                ('alokasi_blok', models.CharField(blank=True, max_length=20, null=True, verbose_name='Yard Block')),
                ('alokasi_bay', models.CharField(blank=True, max_length=10, null=True, verbose_name='Yard Bay')),
                ('alokasi_row', models.CharField(blank=True, max_length=10, null=True, verbose_name='Yard Row')),
                ('alokasi_tier', models.CharField(blank=True, max_length=10, null=True, verbose_name='Yard Tier')),
                ('waktu_masuk', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Waktu Gate In')),
                ('waktu_mulai_proses', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Mulai Proses')),
                ('waktu_selesai', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Selesai Yard')),
                ('waktu_keluar', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Gate Out')),
                ('catatan', models.TextField(blank=True, null=True, verbose_name='Catatan Operasional')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entries', to='masterdata.container', verbose_name='Peti Kemas / Kontainer')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queue_entries', to='masterdata.driver', verbose_name='Sopir Aktual')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_handled', to=settings.AUTH_USER_MODEL, verbose_name='Operator Pendaftar')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queue_entries', to='masterdata.truck', verbose_name='Truk Armada')),
            ],
            options={
                'verbose_name': 'Antrian Truk',
                'verbose_name_plural': 'Antrian Truk',
                'db_table': 'queue_gate_entry',
                'ordering': ['-waktu_masuk'],
            },
        ),
        migrations.CreateModel(
            name='QueueStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_lama', models.CharField(blank=True, choices=[('MENUNGGU', 'Menunggu Buffer Gate'), ('PROSES', 'Sedang Proses di Booth / Yard'), ('TERTAHAN', 'Tertahan / Hold'), ('SELESAI', 'Selesai di Yard'), ('KELUAR', 'Keluar Terminal (Gate Out)')], max_length=25, null=True, verbose_name='Status Lama')),
                ('status_baru', models.CharField(choices=[('MENUNGGU', 'Menunggu Buffer Gate'), ('PROSES', 'Sedang Proses di Booth / Yard'), ('TERTAHAN', 'Tertahan / Hold'), ('SELESAI', 'Selesai di Yard'), ('KELUAR', 'Keluar Terminal (Gate Out)')], max_length=25, verbose_name='Status Baru')),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Keterangan / Alasan')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Waktu Perubahan')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Operator Pengubah')),
                ('queue_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='queue_gate.queueentry', verbose_name='Antrian Terkait')),
            ],
            options={
                'verbose_name': 'Audit Log Status Antrian',
                'verbose_name_plural': 'Audit Log Status Antrian',
                'db_table': 'queue_gate_status_log',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddConstraint(
            model_name='queueentry',
            constraint=models.UniqueConstraint(fields=('tanggal', 'no_antrian'), name='unique_daily_queue_number'),
        ),
    ]
