# Generated by Django 5.1.15 on 2026-09-14 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=30, unique=True, verbose_name='NIP / ID Operator')),
                ('nama', models.CharField(max_length=150, verbose_name='Nama Lengkap Operator')),
                ('booth_aktif', models.CharField(blank=True, choices=[('GATE_IN_01', 'Gate Inbound 01'), ('GATE_IN_02', 'Gate Inbound 02'), ('GATE_IN_03', 'Gate Inbound 03 (Auto OCR)'), ('GATE_IN_04', 'Gate Inbound 04 (Trouble/Hold)'), ('GATE_IN_05', 'Gate Inbound 05 (Empty Return)'), ('GATE_IN_06', 'Gate Inbound 06 (Dedicated)'), ('GATE_OUT_01', 'Gate Outbound 01 (Dispatch)'), ('GATE_OUT_02', 'Gate Outbound 02 (Bypass)'), ('CENTRAL_DESK', 'Central Desk / Supervisor')], max_length=50, null=True, verbose_name='Booth / Gate Aktif')),
                ('shift_aktif', models.CharField(blank=True, choices=[('SHIFT_1', 'Shift 1 (08:00 - 16:00)'), ('SHIFT_2', 'Shift 2 (16:00 - 24:00)'), ('SHIFT_3', 'Shift 3 (00:00 - 08:00)')], max_length=20, null=True, verbose_name='Shift Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operator_profile', to=settings.AUTH_USER_MODEL, verbose_name='Akun User')),
            ],
            options={
                'verbose_name': 'Profil Operator',
                'verbose_name_plural': 'Profil Operator',
                'db_table': 'accounts_operator_profile',
                'ordering': ['nama'],
            },
        ),
    ]
