# Generated by Django 5.1.15 on 2026-09-14 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_kontainer', models.CharField(db_index=True, max_length=15, unique=True, verbose_name='Nomor Kontainer (ISO 6346)')),
                ('ukuran', models.CharField(choices=[('20ft', '20 Feet'), ('40ft', '40 Feet'), ('45ft', '45 Feet')], default='40ft', max_length=10, verbose_name='Ukuran Kontainer')),
                ('tipe', models.CharField(choices=[('DRY', 'Dry / General Purpose'), ('REEFER', 'Refrigerated'), ('FLAT_RACK', 'Flat Rack'), ('OPEN_TOP', 'Open Top'), ('TANK', 'ISO Tank')], default='DRY', max_length=30, verbose_name='Tipe Kontainer')),
                ('kategori', models.CharField(choices=[('IMPORT', 'Import Full'), ('EXPORT', 'Export Full'), ('EMPTY_RETURN', 'Empty Return')], default='IMPORT', max_length=30, verbose_name='Kategori Muatan')),
                ('berat_kotor', models.DecimalField(decimal_places=2, help_text='Berat kotor muatan dalam satuan kilogram (kg)', max_digits=8, verbose_name='Berat Kotor (kg)')),
                ('shipping_line', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shipping Line / Pelayaran')),
                ('seal_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nomor Segel (Seal)')),
                ('ref_dokumen', models.CharField(blank=True, max_length=100, null=True, verbose_name='No Booking / DO / SPPB')),
                ('status_vgm', models.CharField(choices=[('VERIFIED', 'Verified'), ('PENDING', 'Pending')], default='VERIFIED', max_length=20, verbose_name='Status VGM')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
            ],
            options={
                'verbose_name': 'Kontainer',
                'verbose_name_plural': 'Kontainer',
                'db_table': 'masterdata_container',
                'ordering': ['no_kontainer'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150, verbose_name='Nama Lengkap Sopir')),
                ('no_hp', models.CharField(max_length=25, verbose_name='No HP / WhatsApp')),
                ('no_sim', models.CharField(max_length=50, unique=True, verbose_name='Nomor SIM')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
            ],
            options={
                'verbose_name': 'Sopir Truk',
                'verbose_name_plural': 'Sopir Truk',
                'db_table': 'masterdata_driver',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_perusahaan', models.CharField(max_length=150, unique=True, verbose_name='Nama Perusahaan Ekspedisi')),
                ('kode_ekspedisi', models.CharField(blank=True, max_length=30, null=True, verbose_name='Kode Ekspedisi')),
                ('no_telepon', models.CharField(blank=True, max_length=30, null=True, verbose_name='No Telepon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
            ],
            options={
                'verbose_name': 'Perusahaan Ekspedisi',
                'verbose_name_plural': 'Perusahaan Ekspedisi',
                'db_table': 'masterdata_expedition',
                'ordering': ['nama_perusahaan'],
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_polisi', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Nomor Polisi')),
                ('konfigurasi', models.CharField(choices=[('TRAILER_20', 'Trailer 20ft / Single Axle'), ('TRAILER_40', 'Trailer 40ft / Multi Axle'), ('TRONTON', 'Tronton Head Truck'), ('FLATBED', 'Dump / Flatbed Carrier'), ('LOWBED', 'Lowbed Heavy-Lift Carrier')], default='TRAILER_40', max_length=50, verbose_name='Konfigurasi Truk')),
                ('rfid_tag', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='RFID Tag CMS')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trucks', to='masterdata.driver', verbose_name='Sopir Tetap / Default')),
                ('expedisi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trucks', to='masterdata.expedition', verbose_name='Perusahaan Ekspedisi')),
            ],
            options={
                'verbose_name': 'Truk Armada',
                'verbose_name_plural': 'Truk Armada',
                'db_table': 'masterdata_truck',
                'ordering': ['no_polisi'],
            },
        ),
    ]
