# Generated by Django 5.2.17 on 2026-09-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Status Aktif'),
        ),
    ]
